In [3]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(1, 10)
print(a.reshape(3, 3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a1 = np.zeros((1,10))
np.reshape( a1, (2,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
a2 = np.ones((4,4))
a2


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
a2 = np.ones((4,4), dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
a2 = np.ones((1,16), dtype=int)
np.reshape(a2, (4,4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.random.randint(10,50,5) 

array([49, 43, 40, 43, 17], dtype=int32)

In [6]:
a = np.array([10, 20, 30, 40, 50])
a[0:3]
a[-2:]

array([40, 50])

In [8]:
arr = np.array([1,2,3,4,5])
arr[1:5]  # Slicing from index 1 to 3 (exclusive of 4)

array([2, 3, 4, 5])

In [10]:
a = np.array([[1,2,3,4]
              ,[5,6,7,8]
              ,[9,10,11,12]])
print(a[0:2,0:2])  # Accessing element at row 2, column 2


[[1 2]
 [5 6]]


In [12]:
a = np.array([[1,2,3,4]
              ,[5,6,7,8]
              ,[9,10,11,12]])
print(a[::-1])  # Accessing element at row 2, column 2


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [13]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])  # Slicing from index 1 to 3 (exclusive of 4)

[5 4 3 2 1]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)  # Element-wise addition

[5 7 9]


In [15]:
arr = np.array([1,2,3,4])
arr2 = arr*2

In [16]:
arr2

array([2, 4, 6, 8])

In [19]:
arr = np.array([1,2,3,4,5])
arr2 = np.sum(arr)
print(arr2)  # Sum of all elements in the array

15


In [20]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.std(arr))  

3.0
1.4142135623730951


In [21]:
arr = np.array([1,2,3,4,5])
print(np.square(arr))  # Squaring each element in the array

[ 1  4  9 16 25]


In [22]:
arr = np.square([1,2,3,4,5])  # Squaring each element in the array

In [23]:
arr

array([ 1,  4,  9, 16, 25])

In [26]:
arr = np.array([10, 25, 30, 45])
arr2 = np.greater(arr, 20) 
 # Boolean array where elements greater than 20 are True

In [27]:
arr2

array([False,  True,  True,  True])

In [34]:
arr = np.array([10, 25, 30, 45])
arr2 = arr[arr > 20]
print(arr2)  # Boolean array where elements greater than 20 are True

[25 30 45]


In [35]:
arr = np.array([10, 25, 30, 45])
arr2 = arr[arr>15]
arr2.replace(15) 
arr2 # Boolean array where elements greater than 20 are True

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [36]:
arr = np.array([10, 25, 30, 45])
arr[1] = 99

In [37]:
arr

array([10, 99, 30, 45])

In [38]:
arr = np.array([5, 10, 15, 20, 25, 30])
arr[arr> 15] =99
print(arr)  # Replacing elements greater than 15 with 99

[ 5 10 15 99 99 99]


In [39]:
arr = np.array([10, 25, 30, 45])
arr[arr > 15] = 99
print(arr)  # Replacing elements greater than 15 with 99

[10 99 99 99]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
if arr%2 == 0:
    print("Even")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
arr = np.array([1,2,3,4,5,6,7,8])
arr2 = np.sum(arr%2 == 0)  # Summing only even numbers
print(arr2)  # Output the sum of even numbers

4


In [43]:
arr = np.array([-5, 2, -1, 0, 4])
arr2 = arr[arr<0]  # Extracting negative numbers
print(arr2)  # Output the negative numbers  
               

[-5 -1]


In [44]:
arr = np.array([10,50,30,50,70])
arr = arr[arr == 50]  # Extracting elements equal to 50
print(arr)  # Output the elements equal to 50

[50 50]


In [48]:
arr = np.array([10,50,30,50,70])
arr2 = np.where (arr == 50)# Extracting elements equal to 50
print(arr2)  # Output the elements equal to 50

(array([1, 3]),)


In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) 
print(arr.reshape(3,4))# Output the reshaped array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6],
                [7, 8, 9]])
                
arr.ravel()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr = np.array([[1,2,3,4,5,6],[4,5,6,4,5,6],[3,4,6,4,3,4]])
arr = np.hstack(arr)
arr


array([1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 3, 4, 6, 4, 3, 4])

In [83]:
arr = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,2,4,7,9]])
arr = np.hstack(arr)
arr

array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 3, 2, 4, 7, 9])

In [84]:
arr = np.vstack(arr)

In [85]:
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [5],
       [4],
       [3],
       [2],
       [3],
       [2],
       [4],
       [7],
       [9]])

In [86]:
arr = np.eye(4,4)
print (arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
