In [25]:
import numpy as np


In [13]:
np.__version__

'2.1.3'

In [14]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [16]:
arr = np.array(my_list)  #converting list into array
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
print(type(arr))

<class 'numpy.ndarray'>


# .arange()

In [18]:
np.arange(10) # it is same like range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [23]:
np.arange(20,10)  # first arg is always greater that second

array([], dtype=int64)

In [24]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

# .zeros()

In [14]:
np.zeros(5) #parameter tunning

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype = int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros([5,4])   #5 rows , 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# .ones()

# .ones()

it will create a new array filled with the one's

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones(3, dtype = int)

array([1, 1, 1])

In [21]:
np.ones([3,3], dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
arr

array([0, 1, 2, 3, 4, 5])

# rand()

it will create the random values

In [26]:
rand(3,2)

NameError: name 'rand' is not defined

In [27]:
random.rand(3,2)

NameError: name 'random' is not defined

In [28]:
np.random.rand(3,2)

array([[0.31240764, 0.08057437],
       [0.25353502, 0.14535667],
       [0.50918823, 0.72034224]])

In [38]:
np.random.rand(3) #every time we will get new values

array([0.36043829, 0.47143477, 0.13456665])

In [39]:
np.random.randint(4,6) #generate the number between 4 and 6, 

5

In [109]:
np.random.randint(0,10)

6

In [122]:
np.random.randint(1,10,4)

array([4, 3, 2, 2], dtype=int32)

In [124]:
np.random.randint(10,40,(10,8))

array([[10, 35, 30, 34, 35, 18, 32, 33],
       [32, 20, 30, 19, 19, 27, 28, 23],
       [30, 22, 28, 22, 36, 11, 38, 26],
       [10, 28, 13, 16, 37, 14, 37, 29],
       [32, 32, 35, 17, 19, 18, 19, 38],
       [12, 26, 11, 20, 37, 33, 32, 27],
       [22, 15, 37, 27, 18, 37, 25, 31],
       [14, 12, 17, 32, 15, 29, 28, 32],
       [12, 34, 34, 24, 32, 23, 24, 20],
       [29, 15, 32, 28, 12, 27, 13, 26]], dtype=int32)

# Indxing and slicing in matrix

In [126]:
n= np.random.randint(10,40,(10,8))
n

array([[36, 33, 32, 38, 12, 30, 21, 15],
       [18, 29, 21, 15, 24, 32, 21, 17],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [27, 34, 34, 18, 13, 23, 18, 13],
       [33, 30, 27, 39, 31, 20, 11, 38],
       [14, 11, 36, 24, 26, 23, 34, 24],
       [13, 35, 20, 25, 29, 34, 39, 23],
       [27, 17, 37, 23, 14, 32, 28, 26],
       [21, 14, 18, 36, 25, 39, 11, 15],
       [38, 12, 21, 33, 12, 16, 18, 20]], dtype=int32)

In [127]:
n[0]

array([36, 33, 32, 38, 12, 30, 21, 15], dtype=int32)

In [128]:
n[5]

array([14, 11, 36, 24, 26, 23, 34, 24], dtype=int32)

In [129]:
n[0:6]

array([[36, 33, 32, 38, 12, 30, 21, 15],
       [18, 29, 21, 15, 24, 32, 21, 17],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [27, 34, 34, 18, 13, 23, 18, 13],
       [33, 30, 27, 39, 31, 20, 11, 38],
       [14, 11, 36, 24, 26, 23, 34, 24]], dtype=int32)

In [130]:
n[1:4]

array([[18, 29, 21, 15, 24, 32, 21, 17],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [27, 34, 34, 18, 13, 23, 18, 13]], dtype=int32)

In [131]:
n[::-1]

array([[38, 12, 21, 33, 12, 16, 18, 20],
       [21, 14, 18, 36, 25, 39, 11, 15],
       [27, 17, 37, 23, 14, 32, 28, 26],
       [13, 35, 20, 25, 29, 34, 39, 23],
       [14, 11, 36, 24, 26, 23, 34, 24],
       [33, 30, 27, 39, 31, 20, 11, 38],
       [27, 34, 34, 18, 13, 23, 18, 13],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [18, 29, 21, 15, 24, 32, 21, 17],
       [36, 33, 32, 38, 12, 30, 21, 15]], dtype=int32)

In [132]:
n[::2]

array([[36, 33, 32, 38, 12, 30, 21, 15],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [33, 30, 27, 39, 31, 20, 11, 38],
       [13, 35, 20, 25, 29, 34, 39, 23],
       [21, 14, 18, 36, 25, 39, 11, 15]], dtype=int32)

In [133]:
n

array([[36, 33, 32, 38, 12, 30, 21, 15],
       [18, 29, 21, 15, 24, 32, 21, 17],
       [20, 35, 33, 37, 24, 22, 16, 15],
       [27, 34, 34, 18, 13, 23, 18, 13],
       [33, 30, 27, 39, 31, 20, 11, 38],
       [14, 11, 36, 24, 26, 23, 34, 24],
       [13, 35, 20, 25, 29, 34, 39, 23],
       [27, 17, 37, 23, 14, 32, 28, 26],
       [21, 14, 18, 36, 25, 39, 11, 15],
       [38, 12, 21, 33, 12, 16, 18, 20]], dtype=int32)

In [134]:
n[0,5] # , means it will print the specific element/position

np.int32(30)

In [135]:
n[5,-3]

np.int32(23)

# .reshape()

In [136]:
np.arange(1,13).reshape(3,4) # print hr numbers as 3 rows snd 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [138]:
np.arange(1,13).reshape(1,12) # it will work with alla the combinations

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [139]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [140]:
np.arange(0,20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [141]:
np.arange(0,20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [142]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [143]:
np.arange(0,20).reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])